In [ ]:
import requests
from bs4 import BeautifulSoup
import re

# 웹서버에 전달할 User-Agent 헤더 설정
headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# 국회의원 300명의 정보를 저장할 List 선언

# 1페이지부터 30페이지까지 순회하면서 Open API(JSON) 요청하기
# 요청 URL : https://www.assembly.go.kr/portal/cnts/cntsNaas/findNaasThx01.json?pageIndex={index}
# 1. requests의 get() 함수로 요청하고 응답받기
# 2. 응답이 정상(res.ok)이면 res.json()['resultList'] 에서 10명씩 꺼내서 List에 추가하기
# 3. 응답이 정상이 아니면 상태코드(res.status_code) 출력하기

# 수집한 데이터의 개수와 앞의 3건 출력하기

In [ ]:
from pprint import pprint

# pprint() 함수로 수집한 데이터 3건을 보기 좋게 출력하기

#### Json 데이터와 상세페이지 스크래핑 데이터 를 혼합해서 상세정보 저장하기

In [ ]:
import requests
from bs4 import BeautifulSoup
import re
from urllib.parse import urljoin

# 국회의원 1명의 상세정보(dict)를 저장할 List 선언

headers = {
    'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'
}

# JSON으로 수집한 member_list_300 을 순회하면서 상세페이지 스크래핑하기
# 1. member['mLinkUrl'] 값으로 상세페이지 URL 만들기 ( https://www.assembly.go.kr + mLinkUrl )
# 2. requests의 get() 함수로 상세페이지 요청하기
# 3. BeautifulSoup 객체 생성하기 ( parser : html.parser )
# 4. select('ul.list li:nth-of-type(n+4)') 로 상세정보를 가진 li 태그들 선택하기
# 5. li 태그에서 dt 태그의 text를 추출해서 dt_list 만들기 ( List Comprehension )
# 6. li 태그에서 dd 태그의 text를 추출하고, 정규식으로 개행/탭 문자를 제거해서 dd_list 만들기
# 7. zip() 함수로 dt_list와 dd_list를 묶어서 dict 객체 생성하기
# 8. JSON 데이터에서 이름(hgNm), 정당(polyNm), 성별(sexGbnNm), 선거구(origNm), 지역비례(electGbnNm) 값을 dict에 추가하기
# 9. 소속위원회(cmitNm)는 콤마(,) 앞의 첫번째 위원회만 저장하기 ( 값이 None 이면 빈 문자열 )
# 10. 당선횟수(reeleGbnNm) 값을 dict에 추가하기
# 11. 이미지(mThumbImgUrl)는 urljoin() 함수로 절대경로 URL을 만들어서 dict에 추가하기
# 12. 1명의 정보가 저장된 dict를 List에 추가하기

# 수집한 데이터의 개수 출력하기

#### 웹스크래핑한 데이터를 Pandas DataFrame객체로 저장하여 분석 및 시각화

In [ ]:
import pandas as pd

# 컬럼명을 지정해서 비어있는 DataFrame 객체 생성하기
# ['이름','정당','선거구','당선횟수','지역비례','성별','소속위원회','이미지','사무실 전화','사무실 호실',
#  '개별 홈페이지','이메일','보좌관','선임비서관','비서관','의원실 안내']

# member_detail_list를 순회하면서 dict 하나를 Row 하나로 생성하고, concat() 함수로 이어붙이기
# from_records() 함수 사용

# 컬럼명(columns)과 shape 확인하고 head(2) 출력하기

In [9]:
# index가 1부터 시작하도록 재설정
# reset_index() 함수와 index 속성 사용하기

RangeIndex(start=1, stop=299, step=1)

In [2]:
import pandas as pd

# data/members.json 파일을 read_json() 함수로 읽어서 DataFrame 객체 생성하기
# shape 확인하기

(296, 16)

In [3]:
# 정당의 unique한 값 확인하기

array(['조국혁신당', '국민의힘', '더불어민주당', '무소속', '진보당', '기본소득당', '개혁신당', '사회민주당'],
      dtype=object)

In [4]:
# 정당별 Row Counting - value_counts() 함수

정당
더불어민주당    162
국민의힘      107
조국혁신당      12
무소속         6
진보당         4
개혁신당        3
기본소득당       1
사회민주당       1
Name: count, dtype: int64

In [5]:
# 당선횟수별 Row Counting

당선횟수
초선    130
재선     78
3선     46
4선     24
5선     14
6선      4
Name: count, dtype: int64

In [7]:
# 당선횟수가 6선인 의원의 이름과 정당 출력하기 - loc[Row 선택, Column 선택]

      이름      정당
251  조경태    국민의힘
258  조정식  더불어민주당
263  주호영    국민의힘
280  추미애  더불어민주당

In [ ]:
# 당선횟수가 5선 또는 6선인 의원의 이름과 정당을 정당순으로 정렬해서 출력하기
# isin() 함수와 sort_values() 함수 사용

In [10]:
# 성별 비율(%) 확인하기 - value_counts(normalize=True)

성별
남    0.787162
여    0.212838
Name: proportion, dtype: float64

In [ ]:
# 선거구별 Row Counting

In [15]:
#선거구2 컬럼을 새로 추가
#경남 창원시성산구 -> 경남
# Series 객체와 StringMethods 객체의 타입 확인하기

#Series객체를 StringMethods 객체로 변환(문자열 슬라이싱을 하기 위해서)

#2글자 슬라이싱 값을 선거구2 라는 컬럼으로 저장

# 인덱스 0~3의 선거구, 선거구2 컬럼값 출력하기

<class 'pandas.core.series.Series'>
<class 'pandas.core.strings.accessor.StringMethods'>

         선거구 선거구2
0       비례대표   비례
1  대구 동구군위군을   대구
2  경기 안양시만안구   경기
3    경북 구미시을   경북

In [16]:
# 선거구2별 Row Counting

선거구2
경기    59
서울    48
비례    46
부산    18
경남    16
경북    13
인천    13
대구    12
충남    10
전남    10
전북     9
충북     8
광주     8
강원     8
대전     7
울산     6
제주     3
세종     2
Name: count, dtype: int64

In [ ]:
# Row Counting - normalize=True 속성은 % (퍼센티지) 비율로 나타냄

In [18]:
# 지역비례(지역구/비례대표)별 Row Counting

지역비례
지역구     250
비례대표     46
Name: count, dtype: int64

In [19]:
# 지역비례(지역구/비례대표) 비율(%) 확인하기

지역비례
지역구     0.844595
비례대표    0.155405
Name: proportion, dtype: float64

In [20]:
# 이미지 컬럼의 마지막 5건 확인하기 - tail() 함수

291    https://www.assembly.go.kr/static/portal/img/o...
292    https://www.assembly.go.kr/static/portal/img/o...
293    https://www.assembly.go.kr/static/portal/img/o...
294    https://www.assembly.go.kr/static/portal/img/o...
295    https://www.assembly.go.kr/static/portal/img/o...
Name: 이미지, dtype: object

In [ ]:
from IPython.display import Image, display

# sample() 함수로 이미지 URL 3건을 추출해서 출력하기
# display(Image(url=img_url)) 함수로 이미지 출력해보기

### 시각화
* Image 출력 - Image 객체, diplay() 함수 사용
* seaborn - countplot, distplot, heatmap Plot 그려보기
* maplotlib - histogram, pie  Plot 그려보기
* 한글폰트 설정

In [22]:
%matplotlib inline

In [23]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

import seaborn as sns

In [25]:
# 폰트이름과 폰트파일 정보 출력하기 - list comprehension ( 'Mal' 이 포함된 폰트만 )

[('Malgun Gothic', 'C:\\Windows\\Fonts\\malgunbd.ttf'),
 ('Malgun Gothic', 'C:\\Windows\\Fonts\\malgunsl.ttf'),
 ('Malgun Gothic', 'C:\\Windows\\Fonts\\malgun.ttf')]

In [26]:
#한글폰트 path 설정

# font의 파일정보로 font name을 알아내기

# matplotlib의 rc(run command) 함수를 사용해서 폰트이름 설정

Malgun Gothic

### Seaborn 의 막대 그래프
* barplot - x축과 y축을 둘 다 설정할 수 있음
* countplot - x축 이나 y축 중에서 하나만 설정할 수 있음
    * 범주형 속성을 가지는 데이터들의 히스토그램을 보여준다.
    * 종류별로 count를 보여주는 Plot이다.

In [28]:
# 정당명이 빈도순으로 정렬된 index 확인하기

Index(['더불어민주당', '국민의힘', '조국혁신당', '무소속', '진보당', '개혁신당', '기본소득당', '사회민주당'], dtype='object', name='정당')

In [ ]:
# subplots() 함수로 3행 1열의 axes 객체를 생성하고 figure 크기 설정하기

# seaborn의 countplot() 함수 - 정당 ( order 옵션 : 빈도순 정렬, hue 옵션 : 색상 구분 )

# seaborn의 countplot() 함수 - 당선횟수

# seaborn의 countplot() 함수 - 성별 ( y축으로 설정 )

# plt.show()

#### Matplotlib 의 Pie Plot 그려보기

In [ ]:
# 선거구2의 비율(%)을 구해서 cdf 변수에 저장하기

In [ ]:
# cdf의 index(선거구 이름) 확인하기

In [ ]:
# figure size 설정

# pie() 함수 - pie plot을 그려주는 함수 ( labels, autopct, startangle, shadow 옵션 )

# pie plot을 그릴때 원의 형태를 유지하도록 하는 설정 - axis('equal')

# title 설정하고 show() 함수 호출하기

#### Seaborn의 HistPlot (분포도)
* 히스토그램은 구간에 따른 Count를 표현하기 때문에, y는 count로 고정되어 있어 x값만 설정하면 됩니다. ( x 와 y 중에서 하나만 설정하면 됩니다.)
* hue 옵션은 값에 따라 Plot의 색을 다르게 표현할 수 있다.
* multiple = 'dodge'|'stack'

In [ ]:
# subplots() 함수로 axes 객체를 생성하고 figure 크기 설정하기

# seaborn의 histplot() 함수 - x는 정당, hue는 성별, multiple='dodge'
# palette 옵션으로 남/여 색상을 지정하고, shrink 옵션으로 막대 폭 조정하기

In [ ]:
# 조국혁신당 소속 의원의 이름과 성별 출력하기

In [ ]:
# 조국혁신당 소속 의원을 성별로 그룹핑해서 count 하기 - groupby() 함수

#### 다중 빈도 막대 그래프 catplot
* 다중 빈도 막대그래프는 countplot() 또는 catplot() 이 있습니다.
* hue 옵션은 변량을 색상으로 구분하는 파라미터입니다.

In [ ]:
# 선거구 이름들이 빈도순으로 정렬된 리스트입니다.

In [ ]:
# seaborn의 catplot() 함수 - y는 선거구2, hue는 성별, kind='count'
# palette 옵션으로 색상 지정하고, order 옵션으로 빈도순 정렬하기

#### 히스토그램을 만드는 displot
* hue와 palette를 사용하여 색상을 지정할 수 있습니다.
* col 옵션은 성별에 따라 서브플롯을 나누어서 그려줍니다.

In [ ]:
# seaborn의 displot() 함수 - x는 당선횟수
# hue 옵션 : 성별에 따라 색상 구분
# col 옵션 : 성별에 따라 캔버스 구분
# palette 옵션 : 색상 지정
# kde 옵션 : 커널 밀도 추정 곡선 추가 (선택 사항)
# height, aspect 옵션 : 각 플롯의 높이와 가로 세로 비율